version: '3.1'
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 123456
  redis:
    image: redis
    ports:
      - "6379:6379"
  rabbitmq:
    image: rafakato/rabbitmq-delayed-message-exchange
    ports:
      - "5672:5672"

