insert into bank(bacen_cod, name) values(001, 'BANCO DO BRASIL S.A. Banco do Brasil ');
insert into bank(bacen_cod, name) values(003, 'BANCO DA AMAZONIA S.A.');
insert into bank(bacen_cod, name) values(004, 'BANCO DO NORDESTE DO BRASIL S.A');
insert into bank(bacen_cod, name) values(012, 'BANCO STANDARD DE INVESTIMENTOS S.A. Banco');
insert into bank(bacen_cod, name) values(014, 'NATIXIS BRASIL S.A. BANCO MÚLTIPL');
insert into bank(bacen_cod, name) values(019, 'BANCO AZTECA DO BRASIL S.A');
insert into bank(bacen_cod, name) values(021, 'BANESTES S.A. BANCO DO ESTADO DO ESPIRITO SANT');
insert into bank(bacen_cod, name) values(024, 'BANCO DE PERNAMBUCO S.A. - BANDEP');
insert into bank(bacen_cod, name) values(025, 'BANCO ALFA S.A.');
insert into bank(bacen_cod, name) values(029, 'BANCO BANERJ S.A');
insert into bank(bacen_cod, name) values(031, 'BANCO BEG S.A');
insert into bank(bacen_cod, name) values(033, 'BANCO SANTANDER (BRASIL) S.A');
insert into bank(bacen_cod, name) values(036, 'BANCO BRADESCO BBI S.A');
insert into bank(bacen_cod, name) values(037, 'BANCO DO ESTADO DO PARÁ S.A');
insert into bank(bacen_cod, name) values(040, 'BANCO CARGILL S.A');
insert into bank(bacen_cod, name) values(041, 'BANCO DO ESTADO DO RIO GRANDE DO SUL S.A');
insert into bank(bacen_cod, name) values(044, 'BANCO BVA S.A');
insert into bank(bacen_cod, name) values(045, 'BANCO OPPORTUNITY S.A');
insert into bank(bacen_cod, name) values(047, 'BANCO DO ESTADO DE SERGIPE S.A');
insert into bank(bacen_cod, name) values(062, 'HIPERCARD BANCO MÚLTIPLO S.A');
insert into bank(bacen_cod, name) values(063, 'BANCO IBI S.A. - BANCO MÚLTIPL');
insert into bank(bacen_cod, name) values(065, 'BANCO LEMON S.A');
insert into bank(bacen_cod, name) values(066, 'BANCO MORGAN STANLEY S.A');
insert into bank(bacen_cod, name) values(069, 'BPN BRASIL BANCO MÚLTIPLO S.A');
insert into bank(bacen_cod, name) values(070, 'BRB - BANCO DE BRASILIA S.A');
insert into bank(bacen_cod, name) values(072, 'BANCO RURAL MAIS S.A');
insert into bank(bacen_cod, name) values(073, 'BB BANCO POPULAR DO BRASIL S.A');
insert into bank(bacen_cod, name) values(074, 'BANCO J. SAFRA S.A');
insert into bank(bacen_cod, name) values(075, 'BANCO CR2 S/A');
insert into bank(bacen_cod, name) values(076, 'BANCO KDB DO BRASIL S.A');
insert into bank(bacen_cod, name) values(077, 'BANCO INTERMEDIUM S/');
insert into bank(bacen_cod, name) values(078, 'BES INVESTIMENTO DO BRASIL S.A. - BANCO DE INVESTIMENTO Banco');
insert into bank(bacen_cod, name) values(079, 'JBS BANCO S/');
insert into bank(bacen_cod, name) values(081, 'CONCÓRDIA BANCO S.A');
insert into bank(bacen_cod, name) values(082, 'BANCO TOPÁZIO S.A');
insert into bank(bacen_cod, name) values(083, 'BANCO DA CHINA BRASIL S.');
insert into bank(bacen_cod, name) values(096, 'BANCO BM&F DE SERVIÇOS DE LIQUIDAÇÃO E CUSTÓDIA S.A.');
insert into bank(bacen_cod, name) values(104, 'CAIXA ECONOMICA FEDERAL Caixa E');
insert into bank(bacen_cod, name) values(107, 'BANCO BBM S/');
insert into bank(bacen_cod, name) values(151, 'BANCO NOSSA CAIXA S.A');
insert into bank(bacen_cod, name) values(184, 'BANCO ITAÚ BBA S.A');
insert into bank(bacen_cod, name) values(204, 'BANCO BRADESCO CARTÕES S.A');
insert into bank(bacen_cod, name) values(208, 'BANCO UBS PACTUAL S.A');
insert into bank(bacen_cod, name) values(212, 'BANCO MATONE S.A');
insert into bank(bacen_cod, name) values(213, 'BANCO ARBI S.A.');
insert into bank(bacen_cod, name) values(214, 'BANCO DIBENS S.A');
insert into bank(bacen_cod, name) values(215, 'BANCO COMERCIAL E DE INVESTIMENTO SUDAMERIS S.A');
insert into bank(bacen_cod, name) values(217, 'BANCO JOHN DEERE S.A');
insert into bank(bacen_cod, name) values(218, 'BANCO BONSUCESSO S.A');
insert into bank(bacen_cod, name) values(222, 'BANCO CALYON BRASIL S.A');
insert into bank(bacen_cod, name) values(224, 'BANCO FIBRA S.A');
insert into bank(bacen_cod, name) values(225, 'BANCO BRASCAN S.A');
insert into bank(bacen_cod, name) values(229, 'BANCO CRUZEIRO DO SUL S.A');
insert into bank(bacen_cod, name) values(230, 'UNICARD BANCO MÚLTIPLO S.A');
insert into bank(bacen_cod, name) values(233, 'BANCO GE CAPITAL S.A');
insert into bank(bacen_cod, name) values(237, 'BANCO BRADESCO S.A');
insert into bank(bacen_cod, name) values(241, 'BANCO CLASSICO S.A');
insert into bank(bacen_cod, name) values(243, 'BANCO MÁXIMA S.A.');
insert into bank(bacen_cod, name) values(246, 'BANCO ABC BRASIL S.A');
insert into bank(bacen_cod, name) values(248, 'BANCO BOAVISTA INTERATLANTICO S.A');
insert into bank(bacen_cod, name) values(249, 'BANCO INVESTCRED UNIBANCO S.A');
insert into bank(bacen_cod, name) values(250, 'BANCO SCHAHIN S.A');
insert into bank(bacen_cod, name) values(254, 'PARANÁ BANCO S.A');
insert into bank(bacen_cod, name) values(263, 'BANCO CACIQUE S.A');
insert into bank(bacen_cod, name) values(265, 'BANCO FATOR S.A');
insert into bank(bacen_cod, name) values(266, 'BANCO CEDULA S.A');
insert into bank(bacen_cod, name) values(300, 'BANCO DE LA NACION ARGENTINA Banco Comercial Estrangeiro ');
insert into bank(bacen_cod, name) values(318, 'BANCO BMG S.A');
insert into bank(bacen_cod, name) values(320, 'BANCO INDUSTRIAL E COMERCIAL S.A');
insert into bank(bacen_cod, name) values(341, 'BANCO ITAÚ S.A');
insert into bank(bacen_cod, name) values(366, 'BANCO SOCIETE GENERALE BRASIL S.A');
insert into bank(bacen_cod, name) values(370, 'BANCO WESTLB DO BRASIL S.A');
insert into bank(bacen_cod, name) values(376, 'BANCO J.P. MORGAN S.A');
insert into bank(bacen_cod, name) values(389, 'BANCO MERCANTIL DO BRASIL S.A');
insert into bank(bacen_cod, name) values(394, 'BANCO FINASA BMC S.A');
insert into bank(bacen_cod, name) values(399, 'HSBC BANK BRASIL S.A. - BANCO MULTIPL');
insert into bank(bacen_cod, name) values(409, 'UNIBANCO-UNIAO DE BANCOS BRASILEIROS S.A');
insert into bank(bacen_cod, name) values(412, 'BANCO CAPITAL S.A');
insert into bank(bacen_cod, name) values(422, 'BANCO SAFRA S.A');
insert into bank(bacen_cod, name) values(453, 'BANCO RURAL S.A');
insert into bank(bacen_cod, name) values(456, 'BANCO DE TOKYO-MITSUBISHI UFJ BRASIL S/');
insert into bank(bacen_cod, name) values(464, 'BANCO SUMITOMO MITSUI BRASILEIRO S.A');
insert into bank(bacen_cod, name) values(473, 'BANCO CAIXA GERAL - BRASIL S.A');
insert into bank(bacen_cod, name) values(477, 'CITIBANK N.A. Banco Comercial Estrangeiro ');
insert into bank(bacen_cod, name) values(479, 'BANCO ITAUBANK S.A');
insert into bank(bacen_cod, name) values(487, 'DEUTSCHE BANK S.A. - BANCO ALEMA');
insert into bank(bacen_cod, name) values(488, 'JPMORGAN CHASE BANK, NATIONAL ASSOCIATION Banco Comercial Estrangeiro ');
insert into bank(bacen_cod, name) values(492, 'ING BANK N.V. Banco Comercial Estrangeiro ');
insert into bank(bacen_cod, name) values(494, 'BANCO DE LA REPUBLICA ORIENTAL DEL URUGUAY Banco Comercial Estrangeiro ');
insert into bank(bacen_cod, name) values(495, 'BANCO DE LA PROVINCIA DE BUENOS AIRES Banco Comercial Estrangeiro ');
insert into bank(bacen_cod, name) values(505, 'BANCO CREDIT SUISSE (BRASIL) S.A');
insert into bank(bacen_cod, name) values(600, 'BANCO LUSO BRASILEIRO S.A');
insert into bank(bacen_cod, name) values(604, 'BANCO INDUSTRIAL DO BRASIL S.A');
insert into bank(bacen_cod, name) values(610, 'BANCO VR S.A');
insert into bank(bacen_cod, name) values(611, 'BANCO PAULISTA S.A.');
insert into bank(bacen_cod, name) values(612, 'BANCO GUANABARA S.A');
insert into bank(bacen_cod, name) values(613, 'BANCO PECUNIA S.A');
insert into bank(bacen_cod, name) values(623, 'BANCO PANAMERICANO S.A');
insert into bank(bacen_cod, name) values(626, 'BANCO FICSA S.A');
insert into bank(bacen_cod, name) values(630, 'BANCO INTERCAP S.A');
insert into bank(bacen_cod, name) values(633, 'BANCO RENDIMENTO S.A.');
insert into bank(bacen_cod, name) values(634, 'BANCO TRIANGULO S.A');
insert into bank(bacen_cod, name) values(637, 'BANCO SOFISA S.A');
insert into bank(bacen_cod, name) values(638, 'BANCO PROSPER S.A');
insert into bank(bacen_cod, name) values(641, 'BANCO ALVORADA S.A');
insert into bank(bacen_cod, name) values(643, 'BANCO PINE S.A');
insert into bank(bacen_cod, name) values(652, 'ITAÚ UNIBANCO BANCO MÚLTIPLO S.A');
insert into bank(bacen_cod, name) values(653, 'BANCO INDUSVAL S.A.');
insert into bank(bacen_cod, name) values(654, 'BANCO A.J. RENNER S.A');
insert into bank(bacen_cod, name) values(655, 'BANCO VOTORANTIM S.A');
insert into bank(bacen_cod, name) values(707, 'BANCO DAYCOVAL S.A');
insert into bank(bacen_cod, name) values(719, 'BANIF - BANCO INTERNACIONAL DO FUNCHAL (BRASIL), S.A');
insert into bank(bacen_cod, name) values(721, 'BANCO CREDIBEL S.A');
insert into bank(bacen_cod, name) values(734, 'BANCO GERDAU S.');
insert into bank(bacen_cod, name) values(735, 'BANCO POTTENCIAL S.A.');
insert into bank(bacen_cod, name) values(738, 'BANCO MORADA S.');
insert into bank(bacen_cod, name) values(739, 'BANCO BGN S.A');
insert into bank(bacen_cod, name) values(740, 'BANCO BARCLAYS S.A');
insert into bank(bacen_cod, name) values(741, 'BANCO RIBEIRAO PRETO S.A');
insert into bank(bacen_cod, name) values(743, 'BANCO SEMEAR S.A');
insert into bank(bacen_cod, name) values(745, 'BANCO CITIBANK S.A');
insert into bank(bacen_cod, name) values(746, 'BANCO MODAL S.A');
insert into bank(bacen_cod, name) values(747, 'BANCO RABOBANK INTERNATIONAL BRASIL S.A');
insert into bank(bacen_cod, name) values(748, 'BANCO COOPERATIVO SICREDI S.A. Banco Múlt');
insert into bank(bacen_cod, name) values(749, 'BANCO SIMPLES S.A');
insert into bank(bacen_cod, name) values(751, 'DRESDNER BANK BRASIL S.A. BANCO MULTIPL');
insert into bank(bacen_cod, name) values(752, 'BANCO BNP PARIBAS BRASIL S.A');
insert into bank(bacen_cod, name) values(753, 'NBC BANK BRASIL S. A. - BANCO MÚLTIPL');
insert into bank(bacen_cod, name) values(756, 'BANCO COOPERATIVO DO BRASIL S.A. - BANCOOB Banco Comer');
insert into bank(bacen_cod, name) values(757, 'BANCO KEB DO BRASIL S.A.');