package br.com.unopay.api.config

object QueuesScala {

  final val NOTIFICATION = Queues.NOTIFICATION
  final val BATCH_CLOSING = Queues.BATCH_CLOSING
  final val PAYMENT_REMITTANCE = Queues.PAYMENT_REMITTANCE
  final val CREDIT_PROCESSED = Queues.CREDIT_PROCESSED
  final val ORDER_CREATED = Queues.ORDER_CREATED
  final val ORDER_UPDATED = Queues.ORDER_UPDATED
  final val HIRER_CREDIT_CREATED = Queues.HIRER_CREDIT_CREATED
  final val HIRER_BILLING_CREATED = Queues.HIRER_BILLING_CREATED
  final val BONUS_BILLING_CREATED = Queues.BONUS_BILLING_CREATED
  final val DLQ_NOTIFICATION = Queues.DLQ_NOTIFICATION
  final val DLQ_BATCH_CLOSING = Queues.DLQ_BATCH_CLOSING
  final val DLQ_PAYMENT_REMITTANCE = Queues.DLQ_PAYMENT_REMITTANCE
  final val DLQ_CREDIT_PROCESSED = Queues.DLQ_CREDIT_PROCESSED
  final val DLQ_ORDER_CREATED = Queues.DLQ_ORDER_CREATED
  final val DLQ_HIRER_BILLING_CREATED = Queues.DLQ_HIRER_BILLING_CREATED
  final val DLQ_HIRER_CREDIT_CREATED = Queues.DLQ_HIRER_CREDIT_CREATED
  final val DLQ_ORDER_UPDATED = Queues.DLQ_ORDER_UPDATED
  final val DLQ_BONUS_BILLING_CREATED = Queues.DLQ_BONUS_BILLING_CREATED
  final val DURABLE_CONTAINER = Queues.DURABLE_CONTAINER
}
