unopay:
  api: localhost:8080
  resetPassword:
      url: 'http://unpay.qa.unvlocal.com.br/#/password/'
  notification:
    defaultTemplate: "email-templates/%s/%s.html"
    subjectByEvent:
      'PASSWORD_RESET' : "Foi requisitado a mudança de senha"
      'CREATE_PASSWORD' : "Crie sua nova senha"
      'USER_CREATED' : "Seu usuario foi criado"
    defaultMail:
      from: 'no-reply@roadcard.com.br'
      personalFrom: 'RoadCard'
spring:
  rabbitmq:
      host: rabbit.unvlocal.com.br
      port: 5672
      username: user
      password: user
  mail:
    default-encoding: UTF-8
    host: localhost
    port: 1025
    test-connection: false
    properties:
      mail.smtp.host: smtp.gmail.com