client:
  wingoo:
    user: admin
    password: wingoo!#2018
    application: 5ae0973f07f4f19d8b000006
    api: http://dev-wingoo.herokuapp.com/api
payment:
  gateway:
    config:
      shopId: 21985337
      shopKey: 4876228797067177
      mode: TEST
      endpointHost: secure.payzen.com.br
  soap:
      santander:
        cobranca-online:
          dlb-wsdl-location: classpath:wsdl/DLB/TicketEndpointService.wsdl
          dlb-transacional-service: "http://impl.webservice.dl.app.bsbr.altec.com/"
          ymb-wsdl-location: classpath:wsdl/YMB/CobrancaEndpointService.wsdl
          ymb-transacional-service: "http://impl.webservice.ymb.app.bsbr.altec.com/"
          enviroment: 'T'
unopay:
  credit:
    defaultCreditInsertionType: 'BOLETO'
  api: localhost:8080
  resetPassword:
      url: 'http://unopay.qa.unvlocal.com.br/#/page/password/'
  file-uploader:
    configs:
      avatar:
        folder: avatar
      ciot:
        folder: ciot
addressSearch:
  url: http://api.postmon.com.br/v1/cep/
amazon:
  s3:
    bucketName: unopay-files
    cdn:
      uri: https://s3-us-west-2.amazonaws.com/unopay-files
    accessKey: AKIAIVBZ43OSHKREK4XQ
    secretKey: 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
multipart:
  max-file-size: 9000Kb
logging:
  level:
    org:
      hibernate:
        type: info
spring:
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false

  encryptor:
    password: teste
  redis:
    host: redis.unvlocal.com.br
    port: 6379
  rabbitmq:
    host: rabbit.unvlocal.com.br
    port: 5672
    username: unopay
    password: unopay
  mail:
    default-encoding: UTF-8
    host: localhost
    port: 1025
    test-connection: false
    properties:
      mail.smtp.host: smtp.gmail.com
