payment:
  gateway:
    config:
      shopId: 21985337
      shopKey: 4876228797067177
      mode: TEST
      endpointHost: secure.payzen.com.br
soap:
  pamcary:
    partner-number: '24122925000173'
  client:
    wsdl-location: classpath:wsdl/WSTransacional-wsdl.xml
    transacional-service: "http://webservice.pamcard.jee.pamcary.com.br"
    ssl:
      key-store: classpath:wsdl/unovation.p12
      key-store-password: 'UFK#@01a'
      trust-store: classpath:wsdl/cacerts
      trust-store-password: 'changeit'
logging:
  file: /var/unopay/unpay-api.log
server:
  port: 7070
unopay:
  credit:
    defaultCreditInsertionType: 'BOLETO'
  api: 10.10.0.193:7070
  resetPassword:
        url: 'http://qualidade.roadcard.com.br/plataformaprepaga/#/page/password/'
  notification:
    defaultTemplate: "email-templates/%s/%s.html"
    subjectByEvent:
      'PASSWORD_RESET' : "Foi requisitado a mudança de senha"
      'CREATE_PASSWORD' : "Crie sua nova senha"
      'USER_CREATED' : "Seu usuario foi criado"
      'BATCH_CLOSED' : "Lote fechado."
      'REMITTANCE_CREATED' : "Resumo de processamento – Remessa Débito"
    defaultMail:
      from: 'no-reply@roadcard.com.br'
      personalFrom: 'RoadCard'
  file-uploader:
    configs:
      avatar:
        folder: avatar
      ciot:
        folder: ciot
      receipt:
        folder: nfe
amazon:
  s3:
    bucketName: unopay-files
    cdn:
      uri: https://s3-us-west-2.amazonaws.com/unopay-files
    accessKey: AKIAIVBZ43OSHKREK4XQ
    secretKey: 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
multipart:
  max-file-size: 9000Kb
spring:
  encryptor:
    password: vEexq7mVjQj948B7
  jpa:
    hibernate.ddl-auto: none
    database-platform: org.hibernate.dialect.Oracle10gDialect
    generate-ddl: false
    database: ORACLE
  datasource:
    url: jdbc:oracle:thin:@10.10.0.94:1521:ORCLD
    username: road_pp_h
    password: road_pp_h
    driverClassName: oracle.jdbc.OracleDriver
  redis:
    host: 10.10.0.193
    port: 6379
  rabbitmq:
    host: 10.10.0.193
    port: 5672
    username: unopay
    password: unopay
  mail:
    default-encoding: UTF-8
    host:  10.10.0.61
    port: 25
    test-connection: false
    properties:
      mail.smtp.host: smtp.gmail.com