server:
    tomcat:
        max-threads: 800
google:
  url: https://maps.googleapis.com/maps/api/geocode/json
  key: AIzaSyDx_LI5t14-Jsl-mseXpAjVvqUTiUx6dDY
flyway:
    baselineOnMigrate: true
    clean: true
    locations: db/migration/{vendor}, dev/db/migration/{vendor}
health:
  config:
    enabled: false
addressSearch:
  url: http://api.postmon.com.br/v1/cep/
management:
  security:
    enabled: true
  context-path: /devops
spring:
  mvc:
    locale: en_US
  jackson:
    locale: en_US
    mapper:
        DEFAULT_VIEW_INCLUSION: true
    date-format: "yyyy-MM-dd'T'HH:mm:ssZ"
    write-dates-as-timestamps: false
    serialization:
      write-dates-as-timestamps: false
    time-zone: "UTC"
    serialization-inclusion: non_null
    indent_output: true
    deserialization:
        READ_UNKNOWN_ENUM_VALUES_AS_NULL: true
springfox:
  documentation:
    swagger:
      v2:
        path: /docs
unopay:
  payment-instrument:
    bin: 7004
    length: 16
  boleto:
    days_for_apply_penality: 2
    payment_penality_percent: 0.03
    deadline_in_days: 3
    title_protest_days: 5
    title_protest_type: 9
    days_for_close: 10
    folder: boletos
  notification:
    defaultTemplate: "email-templates/%s/%s.html"
    subjectByEvent:
      'PASSWORD_RESET' : "Foi requisitado a mudança de senha"
      'CREATE_PASSWORD' : "Crie sua nova senha"
      'USER_CREATED' : "Seu usuario foi criado"
      'BATCH_CLOSED' : "Lote fechado."
      'REMITTANCE_CREATED' : "Resumo de processamento – Remessa de pagamento"
      'PAYMENT_APPROVED' : "Pagamento aprovado!"
      'PAYMENT_DENIED' : 'Pagamento não aprovado.'
      'BOLETO_ISSUED' : 'Boleto gerado para sua solicitação.'
    defaultFrom:
      from: 'no-reply@unovation.com.br'
      personalFrom: 'Unopay'
    clientFrom:
      15200249000118:
        from: 'no-reply@clinicasclivale.com.br'
        personalFrom: 'Super Saude'
      21902075000138:
        from: 'no-reply@poupesaude.com.br'
        personalFrom: 'Poupe Saude'
      24075280000165:
        from: 'nao-responda@wingoo.com.br'
        personalFrom: 'Clube Wingoo'
soap:
  client:
    ssl:
      key-store: classpath:wsdl/unovation_com_br.p12
      key-store-password: 'uno1407'
quartz:
  delegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
  appMaxJobRetries: 10
  appDelayBetweenFailedJobsInSeconds: 10
