unopay:
  api: localhost:8080
spring:
    jpa:
        hibernate.ddl-auto: nones
    datasource:
        platform: hsqldb
        continueOnError: true
    redis:
      host: 172.17.0.2
      port: 6379
    rabbitmq:
        host: rabbitmq.qa.unvlocal.com.br
        port: 5672
        username: notifications
        password: 1234
    mail:
      default-encoding: UTF-8
      host: localhost
      port: 1025
      test-connection: false
      properties:
        mail.smtp.host: smtp.gmail.com