unopay:
  api: localhost:8080
spring:
    jpa:
        hibernate.ddl-auto: none
    datasource:
        platform: hsqldb
        continueOnError: true
    redis:
      host: localhost
      port: 6379