server:
  port: 7070
unopay:
  api: 10.10.0.193:7070
  resetPassword:
        url: 'http://unopay.qa.unvlocal.com.br/senha/nova'
  notification:
    defaultTemplate: "email-templates/%s/%s.html"
    subjectByEvent:
      'PASSWORD_RESET' : "Foi requisitado a mudança de senha"
      'CREATE_PASSWORD' : "Crie sua nova senha"
      'USER_CREATED' : "Seu usuario foi criado"
    defaultMail:
      from: 'no-reply@roadcard.com.br'
      personalFrom: 'RoadCard'
spring:
    jpa:
        hibernate.ddl-auto: none
        database-platform: org.hibernate.dialect.Oracle10gDialect
        generate-ddl: false
        database: ORACLE
    datasource:
        url: jdbc:oracle:thin:@10.10.0.94:1521:ORCLD
        username: road_pp_h
        password: road_pp_h
        driverClassName: oracle.jdbc.OracleDriver
    redis:
        host: 10.10.0.193
        port: 6379
    rabbitmq:
        host: 10.10.0.193
        port: 5672
        username: guest
        password: guest
    mail:
      default-encoding: UTF-8
      host:  10.10.0.61
      port: 1025
      test-connection: false
      properties:
        mail.smtp.host: smtp.gmail.com