unopay:
  api: localhost:8080
spring:
    jpa:
        hibernate.ddl-auto: nones
    datasource:
        platform: hsqldb
        continueOnError: true
    redis:
      host: 172.17.0.2
      port: 6379