server:
    tomcat:
        max-threads: 800
flyway:
    baselineOnMigrate: true
    clean: true
    locations: db/migration/{vendor}, dev/db/migration/{vendor}
health:
  config:
    enabled: false
addressSearch:
  url: http://api.postmon.com.br/v1/cep/
management:
  security:
    enabled: false
  context-path: /devops
spring:
  mvc:
    locale: en_US
  jackson:
    locale: en_US
    mapper:
        DEFAULT_VIEW_INCLUSION: true
    date-format: "yyyy-MM-dd'T'HH:mm:ssZ"
    write-dates-as-timestamps: false
    time-zone: "UTC"
    serialization-inclusion: non_null
    indent_output: true
    deserialization:
        READ_UNKNOWN_ENUM_VALUES_AS_NULL: true
springfox:
  documentation:
    swagger:
      v2:
        path: /docs
unopay:
  payment-instrument:
    bin: 7004
    length: 16

quartz:
  delegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
  appMaxJobRetries: 10
  appDelayBetweenFailedJobsInSeconds: 10
