unopay:
  api: localhost:8080
  resetPassword:
        url: 'http://unpay.qa.unvlocal.com.br/senha/nova'
  notification:
    defaultTemplate: "email-templates/%s/%s.html"
    subjectByEvent:
      'CREATE_PASSWORD' : "Crie sua nova senha"
      'USER_CREATED' : "Seu usuario foi criado"
    defaultMail:
      from: 'no-reply@roadcard.com.br'
      personalFrom: 'RoadCard'
spring:
    jpa:
        hibernate.ddl-auto: nones
    datasource:
        platform: hsqldb
        continueOnError: true
    redis:
      host: 172.17.0.2
      port: 6379
    rabbitmq:
        host: rabbit.unvlocal.com.br
        port: 5672
        username: user
        password: user
    mail:
      default-encoding: UTF-8
      host: localhost
      port: 1025
      test-connection: false
      properties:
        mail.smtp.host: smtp.gmail.com