INSERT INTO brand_flag(id,name) values ('001','Bandeira Branca');
INSERT INTO brand_flag(id,name) values ('002','BR');
INSERT INTO brand_flag(id,name) values ('003','Ipiranga');
INSERT INTO brand_flag(id,name) values ('004','Raízen');
INSERT INTO brand_flag(id,name) values ('005','Alesat');
INSERT INTO brand_flag(id,name) values ('006','SP');
INSERT INTO brand_flag(id,name) values ('007','Sabba');
INSERT INTO brand_flag(id,name) values ('008','Charrua');
INSERT INTO brand_flag(id,name) values ('009','Latina');
INSERT INTO brand_flag(id,name) values ('010','Equador');
INSERT INTO brand_flag(id,name) values ('011','Zema');
INSERT INTO brand_flag(id,name) values ('012','Atem’s');
INSERT INTO brand_flag(id,name) values ('013','Dislub');
INSERT INTO brand_flag(id,name) values ('014','Potencial');
INSERT INTO brand_flag(id,name) values ('015','Total');
INSERT INTO brand_flag(id,name) values ('016','Petrobahia');
INSERT INTO brand_flag(id,name) values ('017','Petroserra');
INSERT INTO brand_flag(id,name) values ('018','Megapetro');
INSERT INTO brand_flag(id,name) values ('019','Rodoil');
INSERT INTO brand_flag(id,name) values ('020','Fan');
INSERT INTO brand_flag(id,name) values ('021','Raízen Mime');
INSERT INTO brand_flag(id,name) values ('022','Setta');
INSERT INTO brand_flag(id,name) values ('023','Simarelli');
INSERT INTO brand_flag(id,name) values ('024','Mazp');
INSERT INTO brand_flag(id,name) values ('025','Taurus');
INSERT INTO brand_flag(id,name) values ('026','Idaza');
INSERT INTO brand_flag(id,name) values ('027','Ciapetro');
INSERT INTO brand_flag(id,name) values ('028','Rio Branco');
INSERT INTO brand_flag(id,name) values ('029','Ruff CJ');
INSERT INTO brand_flag(id,name) values ('030','Saara');
INSERT INTO brand_flag(id,name) values ('031','Temape');
INSERT INTO brand_flag(id,name) values ('032','Rejaile');
INSERT INTO brand_flag(id,name) values ('033','Atlântica');
INSERT INTO brand_flag(id,name) values ('034','Petrox');
INSERT INTO brand_flag(id,name) values ('035','RM');
INSERT INTO brand_flag(id,name) values ('036','Walendowsky');
INSERT INTO brand_flag(id,name) values ('037','Federal');
INSERT INTO brand_flag(id,name) values ('038','Americanoil');
INSERT INTO brand_flag(id,name) values ('039','Maxsul');
INSERT INTO brand_flag(id,name) values ('040','Acol');
INSERT INTO brand_flag(id,name) values ('041','Small');
INSERT INTO brand_flag(id,name) values ('042','Hora');
INSERT INTO brand_flag(id,name) values ('043','Dibrape');
INSERT INTO brand_flag(id,name) values ('044','Petrox');
INSERT INTO brand_flag(id,name) values ('045','Larco');
INSERT INTO brand_flag(id,name) values ('046','U.B.P.');
INSERT INTO brand_flag(id,name) values ('047','Royal Fic');
INSERT INTO brand_flag(id,name) values ('048','Petro Amazon');
INSERT INTO brand_flag(id,name) values ('049','Polipetro');
INSERT INTO brand_flag(id,name) values ('050','Stang');
INSERT INTO brand_flag(id,name) values ('051','Liderpetro');
INSERT INTO brand_flag(id,name) values ('052','Sul Combustíveis');
INSERT INTO brand_flag(id,name) values ('053','Torrão');
INSERT INTO brand_flag(id,name) values ('054','Pelikano');
INSERT INTO brand_flag(id,name) values ('055','Watt');
INSERT INTO brand_flag(id,name) values ('056','PDV Brasil');
INSERT INTO brand_flag(id,name) values ('057','Ello');
INSERT INTO brand_flag(id,name) values ('058','MMP');
INSERT INTO brand_flag(id,name) values ('059','RDZ');
INSERT INTO brand_flag(id,name) values ('060','Sauro');
INSERT INTO brand_flag(id,name) values ('061','Tobras');
INSERT INTO brand_flag(id,name) values ('062','Petronac');
INSERT INTO brand_flag(id,name) values ('063','GP');
INSERT INTO brand_flag(id,name) values ('064','Jacar');
INSERT INTO brand_flag(id,name) values ('065','Uni');
INSERT INTO brand_flag(id,name) values ('066','Soll');
INSERT INTO brand_flag(id,name) values ('067','Atlantique');
INSERT INTO brand_flag(id,name) values ('068','Montepetro');
INSERT INTO brand_flag(id,name) values ('069','Ello-Puma');
INSERT INTO brand_flag(id,name) values ('070','Flag');
INSERT INTO brand_flag(id,name) values ('071','Fox');
INSERT INTO brand_flag(id,name) values ('072','Global');
INSERT INTO brand_flag(id,name) values ('073','Ipe');
INSERT INTO brand_flag(id,name) values ('074','Podium');
INSERT INTO brand_flag(id,name) values ('075','Rede Brasil');
INSERT INTO brand_flag(id,name) values ('076','Rioil');
INSERT INTO brand_flag(id,name) values ('077','Rumos');
INSERT INTO brand_flag(id,name) values ('078','Triângulo');
INSERT INTO brand_flag(id,name) values ('079','Air BP');
INSERT INTO brand_flag(id,name) values ('080','Aspen');
INSERT INTO brand_flag(id,name) values ('081','Aster');
INSERT INTO brand_flag(id,name) values ('082','Atlanta');
INSERT INTO brand_flag(id,name) values ('083','Bremem');
INSERT INTO brand_flag(id,name) values ('084','D’mais');
INSERT INTO brand_flag(id,name) values ('085','Dínamo');
INSERT INTO brand_flag(id,name) values ('086','Dalçóquio');
INSERT INTO brand_flag(id,name) values ('087','Equatorial');
INSERT INTO brand_flag(id,name) values ('088','Sul');
INSERT INTO brand_flag(id,name) values ('089','Frannel');
INSERT INTO brand_flag(id,name) values ('090','Mercoil');
INSERT INTO brand_flag(id,name) values ('091','Petroalcool');
INSERT INTO brand_flag(id,name) values ('092','Petroforte');
INSERT INTO brand_flag(id,name) values ('093','Petropar');
INSERT INTO brand_flag(id,name) values ('094','Petrosul');
INSERT INTO brand_flag(id,name) values ('095','Seta');
INSERT INTO brand_flag(id,name) values ('096','Spcom');
INSERT INTO brand_flag(id,name) values ('097','T.A. Oil');