package br.com.unopay.api.notification.model;

public enum EventType {

    USER_CREATED, CREATE_PASSWORD, PASSWORD_RESET, BATCH_CLOSED, REMITTANCE_CREATED, PAYMENT_APPROVED, PAYMENT_DENIED,
    BOLETO_ISSUED
}
